#!/usr/bin/env python
"""Parse a chapter file into a tracklist for MusicBrainz."""

import sys
import ffprobe3  # type: ignore

from musicbrainz_video_tracklist import Chapters


if __name__ == "__main__":
    chapters = Chapters(sys.argv[1], ffprobe3.probe)
    try:
        print(chapters)
    except ValueError as ve:
        print(ve)
    except KeyError as ke:
        print(ke)
    except ffprobe3.exceptions.FFprobeMediaFileError as fe:
        print(fe)
