[tool.poetry]
name = "musicbrainz-video-tracklist"
version = "1.0.0"
description = "Generate a tracklist of video recordings for MusicBrainz."
authors = ["Arif Er <arifer612@proton.me>"]
license = "GPLv3"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
bs4 = "^0.0.2"
lxml = "^5.1.0"

[tool.poetry.group.dev.dependencies]
epc = "^0.0.5"
sexpdata = "1.0.0"
importmagic = "^0.1.7"
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
