---
name: Code linting and checking

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "generate-tracklist"

env:
  MODULES: musicbrainz_video_tracklist

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install

      - name: Lint code
        run: poetry run pylint "$MODULES"
      - name: Check static typing
        run: poetry run mypy "$MODULES"
